Lab Exercise: Reading in database files

Create a variable, path, containing the path to the baseball.db contained in resources/
Create a connection, con, that is connected to database at path
Create a variable, query, containing a SQL query which reads in all data from the allstarfull table
Create a variable, observations, by using pandas' read_sql


Optional

Create a variable, tables, which reads in all data from the table sqlite_master
Pretend that you were interesting in creating a new baseball hall of fame. Join and analyze the tables to evaluate the top 3 all time best baseball players.

In [2]:
import pandas as pd
import sqlite3 as sq3

In [3]:
import os
import urllib.request

# Initialize path to SQLite
path = "baseball.db"
data = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0232EN-SkillsNetwork/asset/baseball.db"

if not os.path.exists(path) or os.path.getsize(path) == 0:
    urllib.request.urlretrieve(data, path)

In [11]:
# Create a connection, `con`, that is connected to database at `path`
con = sq3.Connection(path)


# Create a variable, `query`, containing a SQL query which reads in all data from the `` table
query = "SELECT * FROM allstarfull;"

allstarfull_observation = pd.read_sql(query, con)
allstarfull_observation.head()

,index,playerID,yearID,gameNum,gameID,teamID,lgID,GP,startingPos
0,0,gomezle01,1933,0,ALS193307060,NYA,AL,1.0,1.0
1,1,ferreri01,1933,0,ALS193307060,BOS,AL,1.0,2.0
2,2,gehrilo01,1933,0,ALS193307060,NYA,AL,1.0,3.0
3,3,gehrich01,1933,0,ALS193307060,DET,AL,1.0,4.0
4,4,dykesji01,1933,0,ALS193307060,CHA,AL,1.0,5.0

In [12]:
# Create a variable, tables, which reads in all data from the table sqlite_master
all_tables = pd.read_sql('SELECT * FROM sqlite_master', con)
print(all_tables)

    type                  name     tbl_name  rootpage  \
0  table           allstarfull  allstarfull         2
1  index  ix_allstarfull_index  allstarfull         3
2  table               schools      schools        26
3  index      ix_schools_index      schools        31
4  table               batting      batting        99
5  index      ix_batting_index      batting       100

                                                 sql
0  CREATE TABLE "allstarfull" (\n"index" INTEGER,...
1  CREATE INDEX "ix_allstarfull_index"ON "allstar...
2  CREATE TABLE "schools" (\n"index" INTEGER,\n  ...
3  CREATE INDEX "ix_schools_index"ON "schools" ("...
4  CREATE TABLE "batting" (\n"index" INTEGER,\n  ...
5  CREATE INDEX "ix_batting_index"ON "batting" ("...

In [14]:
# Pretend that you were interesting in creating a new baseball hall of fame. Join and analyze the tables to evaluate the top 3 all time best baseball players
best_query = """
SELECT playerID, sum(GP) AS num_games_played, AVG(startingPos) AS avg_starting_position
    FROM allstarfull
    GROUP BY playerID
    ORDER BY num_games_played DESC, avg_starting_position ASC
    LIMIT 3
"""
best = pd.read_sql(best_query, con)
best.head()

    playerID  num_games_played  avg_starting_position
0  musiast01              24.0               6.357143
1   mayswi01              24.0               8.000000
2  aaronha01              24.0               8.470588